---
driver:
  name: gce
  project: protean-bus-122701
  zone: us-east1-c
  email: jalexspringer@gmail.com
  tags:
    - test-kitchen
  service_account_scopes:
    - devstorage.read_write
    - userinfo.email

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  username: vagrant
  ssh_key:
    - ~/.ssh/google_compute_engine

platforms:
  - name: centos-7
    driver:
      image_project: centos-cloud
      image_name: centos-7-v20170327

suites:
  - name: default
    run_list:
      - recipe[mongodb::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
