---
driver:
  name: gce
  project: protean-bus-122701
  zone: us-east1-c
  email: jalexspringer@gmail.com
  tags:
    - test-kitchen
  service_account_scopes:
    - devstorage.read_write
    - userinfo.email
  associate_public_ip: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  username: vagrant
  ssh_key:
    - ~/.ssh/google_compute_engine

platforms:
  - name: centos-7
    driver:
      username: vagrant
      image_project: centos-cloud
      image_name: centos-7-v20170327
      image_family: centos-7

suites:
  - name: default
    data_bags_path: ../lamp/test/fixtures/default/data_bags
    run_list:
      - recipe[tomcat::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
